<a href="https://colab.research.google.com/github/bikram33206/Advanced-house-price-prediction/blob/master/Model1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Predictions on test.csv (Target attribute: outage_type)**

#**Importing Libraries**

In [1]:
import pandas as pd

#**Reading Dataset**

In [2]:
df=pd.read_csv('/content/Broadband_data.csv')
del df['Unnamed: 0']
df.head(2)

      id area_code  ...  volume     transit_server_type
0  13366  area_415  ...       1  transit_server_type_35
1   6783  area_474  ...       2  transit_server_type_35

[2 rows x 8 columns]

In [3]:
df1=df.copy()
del df1['id']
df1.head(2)

  area_code  outage_duration  ... volume     transit_server_type
0  area_415                1  ...      1  transit_server_type_35
1  area_474                0  ...      2  transit_server_type_35

[2 rows x 7 columns]

In [4]:
df1.shape

(48973, 7)

**Converting Outage_type from Categorical to Nuemerical**

In [5]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df1.outage_type)
le.classes_
df1['outage_type']=le.transform(df1.outage_type)

In [6]:
df1.head(2)

  area_code  outage_duration  ... volume     transit_server_type
0  area_415                1  ...      1  transit_server_type_35
1  area_474                0  ...      2  transit_server_type_35

[2 rows x 7 columns]

**Onehot encoding**

In [7]:
new_df=pd.get_dummies(data=df1, columns=['area_code', 'broadband_type','log_report_type','transit_server_type'])

In [8]:
new_df.head(2)

   outage_duration  ...  transit_server_type_transit_server_type_9
0                1  ...                                          0
1                0  ...                                          0

[2 rows x 1248 columns]

**Training Set**

In [9]:
train=new_df.iloc[0:40000,:]
train=train.reset_index()
del train['index']
train.head()

   outage_duration  ...  transit_server_type_transit_server_type_9
0                1  ...                                          0
1                0  ...                                          0
2                0  ...                                          0
3                0  ...                                          0
4                0  ...                                          0

[5 rows x 1248 columns]

In [10]:
train.shape

(40000, 1248)

**Testing Set**

In [11]:
test=new_df.iloc[40000:]
test=test.reset_index()
del test['index']
test.head()

   outage_duration  ...  transit_server_type_transit_server_type_9
0                2  ...                                          0
1                2  ...                                          0
2                2  ...                                          0
3                2  ...                                          0
4                2  ...                                          0

[5 rows x 1248 columns]

In [12]:
test.shape

(8973, 1248)

**Preparing X and y in training set**

In [13]:
y=train.outage_type
y

0        3
1        1
2        1
3        1
4        1
        ..
39995    1
39996    1
39997    1
39998    0
39999    0
Name: outage_type, Length: 40000, dtype: int64

In [14]:
X=train
del X['outage_type']
X.head()

   outage_duration  ...  transit_server_type_transit_server_type_9
0                1  ...                                          0
1                0  ...                                          0
2                0  ...                                          0
3                0  ...                                          0
4                0  ...                                          0

[5 rows x 1247 columns]

**Train and validation split**

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size=0.35, random_state=5)

# **Model Prediction**

**Logistic Regression**

In [16]:
 from sklearn.linear_model import LogisticRegression

In [17]:
 clf = LogisticRegression(multi_class='ovr').fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [18]:
pred=clf.predict(X_val)

In [19]:
clf.predict_proba(X_val)

array([[9.58299207e-01, 4.06457098e-02, 1.26456706e-04, 5.77671153e-04,
        3.50955280e-04],
       [9.82407781e-01, 1.60065551e-02, 3.28892263e-05, 1.46321558e-03,
        8.95591655e-05],
       [9.90267116e-01, 7.70177521e-03, 6.86868298e-05, 1.69902816e-03,
        2.63393927e-04],
       ...,
       [1.03182001e-02, 9.89653332e-01, 2.84063443e-05, 6.12161803e-08,
        1.78628488e-11],
       [9.93189496e-01, 6.70412931e-03, 2.07242744e-05, 7.83607179e-05,
        7.28949478e-06],
       [8.56852488e-02, 8.35448233e-01, 1.13960136e-04, 7.85203826e-02,
        2.32175675e-04]])

In [20]:
clf.score(X_train,y_train) # Accuracy on training set

0.9191538461538461

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val,pred)

array([[7901,  439,    0,    7,    0],
       [ 562, 4879,    0,    3,    0],
       [   3,    0,    0,    0,    0],
       [  93,   84,    0,   21,    0],
       [   5,    0,    0,    0,    3]])

In [22]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
print ('Accuracy Score :',accuracy_score(y_val, pred) ) # Validation Score
print ('Report : ')
print (classification_report(y_val, pred))

Accuracy Score : 0.9145714285714286
Report :
              precision    recall  f1-score   support

           0       0.92      0.95      0.93      8347
           1       0.90      0.90      0.90      5444
           2       0.00      0.00      0.00         3
           3       0.68      0.11      0.18       198
           4       1.00      0.38      0.55         8

    accuracy                           0.91     14000
   macro avg       0.70      0.46      0.51     14000
weighted avg       0.91      0.91      0.91     14000

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

**Prediction on Testing set**

In [23]:
Ytest=test.outage_type # 
Ytest

0       0
1       0
2       0
3       0
4       0
       ..
8968    1
8969    1
8970    1
8971    1
8972    1
Name: outage_type, Length: 8973, dtype: int64

In [26]:
xtest=test
del xtest['outage_type']
xtest.head()

   outage_duration  ...  transit_server_type_transit_server_type_9
0                2  ...                                          0
1                2  ...                                          0
2                2  ...                                          0
3                2  ...                                          0
4                2  ...                                          0

[5 rows x 1247 columns]

In [28]:
pred_test_lr=clf.predict(xtest)

In [29]:
pred_test_lr

array([0, 0, 0, ..., 1, 0, 0])

**Testing Score**

In [30]:
print ('Accuracy Score :',accuracy_score(Ytest, pred_test_lr) )  # Testing Score

Accuracy Score : 0.876629889669007

In [31]:
print ('Report : ')
print (classification_report(Ytest,pred_test_lr))

Report :
              precision    recall  f1-score   support

           0       0.88      0.92      0.90      4888
           1       0.87      0.87      0.87      3881
           2       0.00      0.00      0.00        28
           3       0.73      0.15      0.24       164
           4       0.00      0.00      0.00        12

    accuracy                           0.88      8973
   macro avg       0.50      0.39      0.40      8973
weighted avg       0.87      0.88      0.87      8973

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

**Submission**

In [58]:
dff=pd.read_csv('/content/Broadband_data.csv')
id=dff.iloc[40000:]
id=id.id
id=id.reset_index()

In [59]:
submission=id.id
submission=pd.DataFrame(submission)
submission['pred']=pred_test_lr

In [60]:
outage_type_pred=list(le.inverse_transform(pred_test_lr))
submission['outage_type_pred']=outage_type_pred

In [61]:
submission

         id  pred outage_type_pred
0      3183     0    outage_type_1
1      3183     0    outage_type_1
2      3183     0    outage_type_1
3      3183     0    outage_type_1
4      3183     0    outage_type_1
...     ...   ...              ...
8968  14714     1    outage_type_2
8969  14714     1    outage_type_2
8970  14714     1    outage_type_2
8971   6253     0    outage_type_1
8972   6253     0    outage_type_1

[8973 rows x 3 columns]

In [62]:
del submission['pred']
submission.to_csv('submission_2.csv')